version: '2'

services:

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php

  php:
    build: ./docker/php/
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
        - database
        - redis

    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  database:
        image: mysql:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_ROOT_PASSWORD=secret
          - MYSQL_USER=root
          - MYSQL_PASSWORD=secret
          - MYSQL_DATABASE=laravel
        volumes:
          - "mysql:/var/lib/mysql"
          - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

        ports:
          - "33065:3306"


  redis:
        image: redis:4.0
        ports:
          - "6382:6379"

volumes:
  mysql: { driver: local }
